"""
AI-generated ocean condition predictions, powered by Groq's chat completions API.

This endpoint takes a single point's data (lat/lon, temperature, and whatever
illustrative depth/wave/salinity numbers the frontend already computed) and
asks a Groq-hosted LLM to write a short, plain-English outlook for that spot.

IMPORTANT — this is a narrative generated by a language model reasoning over
the numbers we hand it. It is NOT a physically-modeled ocean/weather forecast.
The frontend must label it as "AI-generated" and must not present it as a
verified prediction. See PredictionPanel.jsx on the frontend for how the
disclaimer is surfaced.

Setup:
    1. Get a free API key at https://console.groq.com
    2. Set it as an environment variable before starting the server:
           export GROQ_API_KEY="gsk_...your_key..."
       (or put it in a .env file and load it with python-dotenv — see
       requirements.txt, "python-dotenv" has been added for this purpose)
    3. Restart uvicorn after setting the key.

If GROQ_API_KEY isn't set, this endpoint returns a 503 with a clear message
rather than crashing the whole app — the rest of the demo (globe, SST, buoy)
works fine without it.
"""

import os
import time

import httpx
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

router = APIRouter()

GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"
# Groq's model lineup changes over time — "llama-3.1-8b-instant" was moved to
# Enterprise-only access, which is why you may see a 404 "model does not
# exist or you do not have access to it" with a standard developer key.
# openai/gpt-oss-20b is on the standard Production Models tier with normal
# developer rate limits, fast, and cheap. If your teammate's Groq account
# has a different model available, swap it here — nothing else needs to change.
GROQ_MODEL = "openai/gpt-oss-20b"

# Very small in-process cache so repeatedly clicking the same spot during a
# demo doesn't burn API calls or make the audience wait every time.
_cache: dict[str, dict] = {}
_CACHE_TTL_SECONDS = 300


class PredictionRequest(BaseModel):
    latitude: float = Field(..., ge=-90, le=90)
    longitude: float = Field(..., ge=-180, le=180)
    temp_c: float
    is_temp_real: bool = False
    depth_m: float | None = None
    wave_m: float | None = None
    salinity_psu: float | None = None


class PredictionResponse(BaseModel):
    latitude: float
    longitude: float
    prediction: str
    model: str
    source: str = "groq"
    cached: bool = False


def _cache_key(req: PredictionRequest) -> str:
    # Round to keep the cache useful even for near-identical clicks.
    return f"{round(req.latitude, 1)}:{round(req.longitude, 1)}:{round(req.temp_c, 1)}"


def _build_prompt(req: PredictionRequest) -> str:
    real_note = (
        "This temperature is a real satellite/buoy reading."
        if req.is_temp_real
        else "This temperature is an illustrative estimate, not a real sensor reading."
    )
    parts = [
        f"Location: latitude {req.latitude:.2f}, longitude {req.longitude:.2f}.",
        f"Sea surface temperature: {req.temp_c:.1f}\u00b0C. {real_note}",
    ]
    if req.depth_m is not None:
        parts.append(f"Approximate depth: {req.depth_m:.0f} m (illustrative).")
    if req.wave_m is not None:
        parts.append(f"Approximate wave height: {req.wave_m:.1f} m (illustrative).")
    if req.salinity_psu is not None:
        parts.append(f"Approximate salinity: {req.salinity_psu:.1f} PSU (illustrative).")

    parts.append(
        "\nWrite a short (2-3 sentence) plain-English outlook for someone "
        "looking at this point on an ocean data map. Mention what conditions "
        "this profile suggests (e.g. typical for the region, notably warm/cold, "
        "rough/calm) in a natural, conversational tone. Do not claim to be an "
        "official forecast, and do not invent specific numeric predictions "
        "beyond what's given."
    )
    return "\n".join(parts)


@router.post("/predict", response_model=PredictionResponse)
def predict_conditions(req: PredictionRequest):
    """
    POST /api/predict

    Body: { "latitude": ..., "longitude": ..., "temp_c": ..., "is_temp_real": ...,
            "depth_m": ..., "wave_m": ..., "salinity_psu": ... }

    Calls Groq's chat completions API with a short prompt built from the
    point's data and returns a short narrative prediction/outlook.
    """
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        raise HTTPException(
            status_code=503,
            detail=(
                "GROQ_API_KEY is not set on the server. Get a free key at "
                "https://console.groq.com and set it as an environment "
                "variable before starting the backend."
            ),
        )

    key = _cache_key(req)
    cached = _cache.get(key)
    if cached and (time.time() - cached["ts"]) < _CACHE_TTL_SECONDS:
        return PredictionResponse(**cached["response"], cached=True)

    prompt = _build_prompt(req)

    try:
        with httpx.Client(timeout=15.0) as client:
            resp = client.post(
                GROQ_API_URL,
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": GROQ_MODEL,
                    "messages": [
                        {
                            "role": "system",
                            "content": (
                                "You are a concise ocean-data assistant embedded in a "
                                "student prototype. Keep responses to 2-3 sentences."
                            ),
                        },
                        {"role": "user", "content": prompt},
                    ],
                    "max_tokens": 200,
                    "temperature": 0.7,
                },
            )
    except httpx.RequestError as e:
        raise HTTPException(status_code=502, detail=f"Could not reach Groq API: {e}")

    if resp.status_code == 401:
        raise HTTPException(status_code=502, detail="Groq API rejected the key (401). Check GROQ_API_KEY.")
    if resp.status_code == 404:
        raise HTTPException(
            status_code=502,
            detail=(
                f"Groq model '{GROQ_MODEL}' is not available on this API key "
                "(404). Check https://console.groq.com/docs/models for models "
                "available on your plan and update GROQ_MODEL in predict.py."
            ),
        )
    if resp.status_code != 200:
        raise HTTPException(
            status_code=502,
            detail=f"Groq API returned {resp.status_code}: {resp.text[:300]}",
        )

    data = resp.json()
    try:
        text = data["choices"][0]["message"]["content"].strip()
    except (KeyError, IndexError):
        raise HTTPException(status_code=502, detail="Unexpected response shape from Groq API.")

    response = PredictionResponse(
        latitude=req.latitude,
        longitude=req.longitude,
        prediction=text,
        model=GROQ_MODEL,
    )
    _cache[key] = {"ts": time.time(), "response": response.model_dump(exclude={"cached"})}
    return response
