// Comprehensive global buoy and autonomous Argo float network.
// Station 41002 is the real NOAA Station with backend CSV linkage.
// Other stations provide continuous global oceanographic observation points.

export const GLOBAL_BUOYS = [
  {
    station_id: '41002',
    name: 'Cape Hatteras (South Hatteras)',
    operator: 'NOAA NDBC',
    ocean: 'North Atlantic',
    latitude: 31.759,
    longitude: -74.936,
    water_temp_c: 29.1,
    air_temp_c: 28.8,
    wave_height_m: 0.8,
    wind_speed_kts: 11.4,
    pressure_hpa: 1017.2,
    salinity_psu: 36.2,
    battery_v: 12.8,
    status: 'ACTIVE',
    depth_m: 3750,
    isPrimary: true,
  },
  {
    station_id: '51001',
    name: 'Northwest Hawaii Mooring',
    operator: 'NOAA NDBC / PacIOOS',
    ocean: 'Central North Pacific',
    latitude: 24.444,
    longitude: -162.008,
    water_temp_c: 26.3,
    air_temp_c: 25.9,
    wave_height_m: 2.1,
    wind_speed_kts: 14.8,
    pressure_hpa: 1016.5,
    salinity_psu: 35.1,
    battery_v: 12.7,
    status: 'ACTIVE',
    depth_m: 4860,
  },
  {
    station_id: '46001',
    name: 'Gulf of Alaska Western Buoy',
    operator: 'NOAA NDBC',
    ocean: 'North Pacific',
    latitude: 56.304,
    longitude: -147.925,
    water_temp_c: 11.2,
    air_temp_c: 9.8,
    wave_height_m: 3.4,
    wind_speed_kts: 22.1,
    pressure_hpa: 1008.4,
    salinity_psu: 32.8,
    battery_v: 12.5,
    status: 'ACTIVE',
    depth_m: 4190,
  },
  {
    station_id: '42001',
    name: 'Mid-Gulf of Mexico Deepwater',
    operator: 'NOAA NDBC',
    ocean: 'Gulf of Mexico',
    latitude: 25.888,
    longitude: -89.658,
    water_temp_c: 30.2,
    air_temp_c: 29.7,
    wave_height_m: 0.9,
    wind_speed_kts: 8.5,
    pressure_hpa: 1015.1,
    salinity_psu: 36.5,
    battery_v: 12.9,
    status: 'ACTIVE',
    depth_m: 3246,
  },
  {
    station_id: '23002',
    name: 'Bay of Bengal Deep Ocean Mooring',
    operator: 'INCOIS / NIOT (India)',
    ocean: 'Bay of Bengal, Indian Ocean',
    latitude: 14.0,
    longitude: 87.0,
    water_temp_c: 29.8,
    air_temp_c: 28.9,
    wave_height_m: 1.6,
    wind_speed_kts: 13.2,
    pressure_hpa: 1009.8,
    salinity_psu: 33.2,
    battery_v: 13.1,
    status: 'ACTIVE',
    depth_m: 3100,
  },
  {
    station_id: '23003',
    name: 'Arabian Sea High-Seas Station',
    operator: 'INCOIS / NIOT (India)',
    ocean: 'Arabian Sea, Indian Ocean',
    latitude: 15.5,
    longitude: 69.2,
    water_temp_c: 28.4,
    air_temp_c: 27.6,
    wave_height_m: 1.9,
    wind_speed_kts: 16.0,
    pressure_hpa: 1011.2,
    salinity_psu: 36.8,
    battery_v: 12.8,
    status: 'ACTIVE',
    depth_m: 3450,
  },
  {
    station_id: '23001',
    name: 'RAMA Equatorial Indian Ocean',
    operator: 'RAMA / NOAA / INCOIS',
    ocean: 'Equatorial Indian Ocean',
    latitude: 0.0,
    longitude: 80.5,
    water_temp_c: 29.5,
    air_temp_c: 28.2,
    wave_height_m: 1.4,
    wind_speed_kts: 10.6,
    pressure_hpa: 1010.5,
    salinity_psu: 34.7,
    battery_v: 12.6,
    status: 'ACTIVE',
    depth_m: 4500,
  },
  {
    station_id: '32012',
    name: 'TAO / TRITON Equatorial Pacific',
    operator: 'PMEL NOAA',
    ocean: 'Equatorial Pacific (El Niño)',
    latitude: 0.0,
    longitude: -140.0,
    water_temp_c: 27.8,
    air_temp_c: 27.1,
    wave_height_m: 1.7,
    wind_speed_kts: 12.4,
    pressure_hpa: 1012.3,
    salinity_psu: 35.3,
    battery_v: 12.9,
    status: 'ACTIVE',
    depth_m: 4320,
  },
  {
    station_id: '62029',
    name: 'Celtic Sea Marine Buoy',
    operator: 'Met Éireann & UK Met Office',
    ocean: 'Northeast Atlantic',
    latitude: 50.8,
    longitude: -11.0,
    water_temp_c: 16.2,
    air_temp_c: 15.1,
    wave_height_m: 2.8,
    wind_speed_kts: 19.5,
    pressure_hpa: 1018.6,
    salinity_psu: 35.4,
    battery_v: 12.7,
    status: 'ACTIVE',
    depth_m: 150,
  },
  {
    station_id: '31001',
    name: 'PIRATA Tropical South Atlantic',
    operator: 'PIRATA / IRD / NOAA',
    ocean: 'South Atlantic',
    latitude: -10.0,
    longitude: -10.0,
    water_temp_c: 25.1,
    air_temp_c: 24.3,
    wave_height_m: 1.5,
    wind_speed_kts: 13.0,
    pressure_hpa: 1015.4,
    salinity_psu: 35.8,
    battery_v: 12.8,
    status: 'ACTIVE',
    depth_m: 4600,
  },
  {
    station_id: '48011',
    name: 'Beaufort Sea Ice Edge Profiler',
    operator: 'International Arctic Buoy Programme',
    ocean: 'Arctic Ocean',
    latitude: 74.2,
    longitude: -140.5,
    water_temp_c: -1.2,
    air_temp_c: -6.5,
    wave_height_m: 0.5,
    wind_speed_kts: 14.1,
    pressure_hpa: 1022.0,
    salinity_psu: 31.4,
    battery_v: 12.4,
    status: 'ACTIVE',
    depth_m: 3800,
  },
  {
    station_id: '55012',
    name: 'Southern Ocean Drake Passage',
    operator: 'SOOS / CSIRO',
    ocean: 'Southern Ocean',
    latitude: -58.5,
    longitude: -62.0,
    water_temp_c: 2.1,
    air_temp_c: 0.8,
    wave_height_m: 4.8,
    wind_speed_kts: 31.2,
    pressure_hpa: 994.2,
    salinity_psu: 34.0,
    battery_v: 12.5,
    status: 'ACTIVE',
    depth_m: 4100,
  },
  {
    station_id: '21001',
    name: 'Kuroshio Extension Observatory (KEO)',
    operator: 'JAMSTEC / NOAA',
    ocean: 'Northwest Pacific',
    latitude: 32.3,
    longitude: 144.6,
    water_temp_c: 24.9,
    air_temp_c: 23.8,
    wave_height_m: 2.2,
    wind_speed_kts: 15.6,
    pressure_hpa: 1014.2,
    salinity_psu: 34.6,
    battery_v: 12.9,
    status: 'ACTIVE',
    depth_m: 5700,
  },
  {
    station_id: 'ARGO-2902781',
    name: 'Deep Argo Profiling Float #2902781',
    operator: 'Global Argo Program / INCOIS',
    ocean: 'Central Indian Basin',
    latitude: -18.4,
    longitude: 76.8,
    water_temp_c: 24.2,
    air_temp_c: 23.5,
    wave_height_m: 1.8,
    wind_speed_kts: 14.0,
    pressure_hpa: 1018.0,
    salinity_psu: 35.6,
    battery_v: 14.2,
    status: 'PROFILING (0-2000m)',
    depth_m: 5120,
    isFloat: true,
  },
]
