// Global major coral reef ecosystems and NOAA Coral Reef Watch (CRW) thermal bleaching vulnerability.

export const CORAL_REEFS = [
  {
    id: 'great-barrier-reef',
    name: 'Great Barrier Reef (Australia)',
    lat: -18.287,
    lon: 147.699,
    area_km2: 348700,
    species_count: '1,500+ fish, 400+ coral',
    alert_level: 'ALERT LEVEL 1',
    alert_color: '#f59e0b',
    dhw_degree_heating_weeks: 4.8,
    status: 'Thermal Stress Watch',
    description: 'The world\'s largest living coral biome. Elevated SST in recent summers has triggered mass bleaching events.',
  },
  {
    id: 'coral-triangle',
    name: 'Coral Triangle (Indo-Pacific)',
    lat: -2.5,
    lon: 128.0,
    area_km2: 6000000,
    species_count: '600+ coral (76% of world total)',
    alert_level: 'WATCH',
    alert_color: '#38bdf8',
    dhw_degree_heating_weeks: 2.1,
    status: 'Normal to Moderate Stress',
    description: 'Global epicenter of marine biodiversity, encompassing waters of Indonesia, Malaysia, Philippines, and Papua New Guinea.',
  },
  {
    id: 'maldives-atolls',
    name: 'Maldives Coral Atolls (Indian Ocean)',
    lat: 3.2,
    lon: 73.2,
    area_km2: 8900,
    species_count: '250+ coral, 1,000+ fish',
    alert_level: 'ALERT LEVEL 2',
    alert_color: '#ef4444',
    dhw_degree_heating_weeks: 8.4,
    status: 'Severe Bleaching Alert',
    description: 'Low-lying atoll systems highly vulnerable to Indian Ocean marine heatwaves and sea level rise.',
  },
  {
    id: 'mesoamerican-reef',
    name: 'Mesoamerican Barrier Reef (Caribbean)',
    lat: 17.5,
    lon: -87.8,
    area_km2: 1000,
    species_count: '65+ coral, 500+ fish',
    alert_level: 'ALERT LEVEL 1',
    alert_color: '#f59e0b',
    dhw_degree_heating_weeks: 5.2,
    status: 'Thermal Warning',
    description: 'Second largest barrier reef in the world, spanning Mexico, Belize, Guatemala, and Honduras.',
  },
  {
    id: 'red-sea-reef',
    name: 'Northern Red Sea Reefs',
    lat: 27.5,
    lon: 34.5,
    area_km2: 4500,
    species_count: '300+ hard coral species',
    alert_level: 'RESILIENT',
    alert_color: '#10b981',
    dhw_degree_heating_weeks: 0.8,
    status: 'High Thermal Tolerance',
    description: 'Known for evolutionary super-corals possessing natural genetic resilience to extreme sea temperatures.',
  },
]
