// Real-world oceanographic currents coordinates, velocities, and properties.
// Currents are major planetary heat conveyors.

export const OCEAN_CURRENTS = [
  {
    id: 'gulf-stream',
    name: 'Gulf Stream & North Atlantic Drift',
    type: 'warm',
    velocity: '2.5 m/s',
    transport: '30-150 Sv',
    description: 'High-velocity western boundary current moving warm tropical water toward Northwest Europe.',
    color: '#ff9d42',
    points: [
      { lat: 24.5, lon: -80.5 },
      { lat: 28.0, lon: -79.5 },
      { lat: 32.5, lon: -76.0 },
      { lat: 36.0, lon: -72.0 },
      { lat: 39.0, lon: -65.0 },
      { lat: 41.5, lon: -50.0 },
      { lat: 46.0, lon: -35.0 },
      { lat: 52.0, lon: -22.0 },
      { lat: 58.0, lon: -10.0 },
      { lat: 64.0, lon: 4.0 },
    ],
  },
  {
    id: 'kuroshio',
    name: 'Kuroshio Current',
    type: 'warm',
    velocity: '2.0 m/s',
    transport: '50 Sv',
    description: 'The "Black Tide" of the western North Pacific, carrying tropical warmth past Taiwan and Japan.',
    color: '#ffaa33',
    points: [
      { lat: 18.0, lon: 124.0 },
      { lat: 22.0, lon: 122.5 },
      { lat: 26.0, lon: 125.0 },
      { lat: 30.5, lon: 130.0 },
      { lat: 33.5, lon: 136.0 },
      { lat: 35.5, lon: 142.0 },
      { lat: 38.0, lon: 152.0 },
      { lat: 40.0, lon: 165.0 },
      { lat: 42.0, lon: 178.0 },
    ],
  },
  {
    id: 'acc',
    name: 'Antarctic Circumpolar Current',
    type: 'cold',
    velocity: '1.2 m/s',
    transport: '140 Sv',
    description: 'The largest current on Earth, circling eastward around Antarctica uninterrupted by land.',
    color: '#4fc3f7',
    points: [
      { lat: -56.0, lon: -70.0 },
      { lat: -53.0, lon: -40.0 },
      { lat: -51.0, lon: -10.0 },
      { lat: -50.0, lon: 20.0 },
      { lat: -51.0, lon: 50.0 },
      { lat: -52.0, lon: 80.0 },
      { lat: -53.0, lon: 110.0 },
      { lat: -55.0, lon: 140.0 },
      { lat: -57.0, lon: 170.0 },
      { lat: -59.0, lon: -160.0 },
      { lat: -60.0, lon: -130.0 },
      { lat: -58.0, lon: -100.0 },
      { lat: -56.0, lon: -70.0 },
    ],
  },
  {
    id: 'california',
    name: 'California Current',
    type: 'cold',
    velocity: '0.4 m/s',
    transport: '10 Sv',
    description: 'Cold eastern boundary current driving rich coastal upwelling along the western coast of North America.',
    color: '#38bdf8',
    points: [
      { lat: 49.0, lon: -128.0 },
      { lat: 43.0, lon: -126.0 },
      { lat: 37.0, lon: -124.0 },
      { lat: 32.0, lon: -120.0 },
      { lat: 25.0, lon: -115.0 },
      { lat: 20.0, lon: -110.0 },
    ],
  },
  {
    id: 'humboldt',
    name: 'Humboldt (Peru) Current',
    type: 'cold',
    velocity: '0.5 m/s',
    transport: '12 Sv',
    description: 'Major productive upwelling current running northward along Chile and Peru, cornerstone of global fisheries.',
    color: '#00e5ff',
    points: [
      { lat: -45.0, lon: -76.0 },
      { lat: -38.0, lon: -75.0 },
      { lat: -30.0, lon: -73.0 },
      { lat: -20.0, lon: -72.0 },
      { lat: -10.0, lon: -80.0 },
      { lat: -4.0, lon: -85.0 },
    ],
  },
  {
    id: 'agulhas',
    name: 'Agulhas Current',
    type: 'warm',
    velocity: '2.2 m/s',
    transport: '70 Sv',
    description: 'Narrow, powerful warm western boundary current flowing southward along the east coast of southern Africa.',
    color: '#ff7043',
    points: [
      { lat: -15.0, lon: 42.0 },
      { lat: -24.0, lon: 36.0 },
      { lat: -30.0, lon: 32.0 },
      { lat: -34.0, lon: 27.0 },
      { lat: -38.0, lon: 20.0 },
      { lat: -40.0, lon: 15.0 },
    ],
  },
  {
    id: 'benguela',
    name: 'Benguela Current',
    type: 'cold',
    velocity: '0.4 m/s',
    transport: '15 Sv',
    description: 'Cold northward current along the southwestern coast of Africa producing intense nutrient-rich upwelling.',
    color: '#26c6da',
    points: [
      { lat: -35.0, lon: 17.0 },
      { lat: -28.0, lon: 14.0 },
      { lat: -20.0, lon: 11.5 },
      { lat: -14.0, lon: 10.0 },
    ],
  },
  {
    id: 'equatorial-pacific',
    name: 'Pacific Equatorial Countercurrent',
    type: 'warm',
    velocity: '0.7 m/s',
    transport: '20 Sv',
    description: 'Eastward-flowing warm current between the North and South Equatorial currents, core of ENSO dynamics.',
    color: '#ffc107',
    points: [
      { lat: 5.0, lon: 135.0 },
      { lat: 5.5, lon: 155.0 },
      { lat: 6.0, lon: 175.0 },
      { lat: 6.5, lon: -165.0 },
      { lat: 6.0, lon: -140.0 },
      { lat: 5.5, lon: -115.0 },
      { lat: 5.0, lon: -90.0 },
    ],
  },
  {
    id: 'indian-monsoon',
    name: 'Indian Monsoon Current (Somali / Arabian Sea)',
    type: 'warm',
    velocity: '1.8 m/s',
    transport: '35 Sv',
    description: 'Reversing seasonal current system driven by the Asian Monsoon, vital to Indian subcontinent climate.',
    color: '#ffb74d',
    points: [
      { lat: 0.0, lon: 45.0 },
      { lat: 7.0, lon: 51.0 },
      { lat: 14.0, lon: 56.0 },
      { lat: 18.0, lon: 63.0 },
      { lat: 15.0, lon: 72.0 },
      { lat: 8.0, lon: 78.0 },
      { lat: 6.0, lon: 86.0 },
      { lat: 12.0, lon: 92.0 },
    ],
  },
  {
    id: 'east-australian',
    name: 'East Australian Current (EAC)',
    type: 'warm',
    velocity: '1.5 m/s',
    transport: '25 Sv',
    description: 'Warm southward current transporting tropical Coral Sea water past Sydney into the Tasman Sea.',
    color: '#ffa726',
    points: [
      { lat: -16.0, lon: 150.0 },
      { lat: -22.0, lon: 153.0 },
      { lat: -28.0, lon: 155.0 },
      { lat: -34.0, lon: 153.5 },
      { lat: -40.0, lon: 150.0 },
    ],
  },
  {
    id: 'labrador',
    name: 'Labrador Current',
    type: 'cold',
    velocity: '0.6 m/s',
    transport: '8 Sv',
    description: 'Cold Arctic current flowing south past Newfoundland, bringing icebergs into Atlantic shipping lanes.',
    color: '#81d4fa',
    points: [
      { lat: 63.0, lon: -60.0 },
      { lat: 57.0, lon: -58.0 },
      { lat: 50.0, lon: -54.0 },
      { lat: 44.0, lon: -50.0 },
      { lat: 41.0, lon: -54.0 },
    ],
  },
]
