export const PLACE_LABELS = [
  { name: 'Pacific Ocean', lat: 0, lon: -160, type: 'ocean' },
  { name: 'Atlantic Ocean', lat: 10, lon: -40, type: 'ocean' },
  { name: 'Indian Ocean', lat: -10, lon: 75, type: 'ocean' },
  { name: 'Southern Ocean', lat: -65, lon: 0, type: 'ocean' },
  { name: 'Arctic Ocean', lat: 85, lon: 0, type: 'ocean' },
  { name: 'Arabian Sea', lat: 15, lon: 65, type: 'sea' },
  { name: 'Bay of Bengal', lat: 15, lon: 88, type: 'sea' },
  { name: 'Mediterranean Sea', lat: 35, lon: 18, type: 'sea' },
  { name: 'Caribbean Sea', lat: 15, lon: -75, type: 'sea' },
  { name: 'South China Sea', lat: 12, lon: 114, type: 'sea' },
  { name: 'Red Sea', lat: 20, lon: 38, type: 'sea' },
  { name: 'Black Sea', lat: 43, lon: 35, type: 'sea' },
  { name: 'Caspian Sea', lat: 42, lon: 51, type: 'sea' },
  { name: 'North Sea', lat: 56, lon: 3, type: 'sea' },
  { name: 'Sea of Japan', lat: 40, lon: 135, type: 'sea' },
  { name: 'Coral Sea', lat: -18, lon: 152, type: 'sea' },
  { name: 'Tasman Sea', lat: -40, lon: 160, type: 'sea' },
  { name: 'Gulf of Mexico', lat: 25, lon: -90, type: 'sea' },
  { name: 'Persian Gulf', lat: 26, lon: 52, type: 'sea' },
  { name: 'Bering Sea', lat: 58, lon: -175, type: 'sea' },
  { name: 'Sea of Okhotsk', lat: 55, lon: 150, type: 'sea' },
  { name: 'Baltic Sea', lat: 58, lon: 20, type: 'sea' },
  { name: 'Andaman Sea', lat: 10, lon: 96, type: 'sea' },
  { name: 'India', lat: 28.6, lon: 77.2, type: 'country' },
  { name: 'United States', lat: 38.9, lon: -77.0, type: 'country' },
  { name: 'Brazil', lat: -15.8, lon: -47.9, type: 'country' },
  { name: 'Russia', lat: 55.75, lon: 37.6, type: 'country' },
  { name: 'China', lat: 39.9, lon: 116.4, type: 'country' },
  { name: 'Australia', lat: -35.3, lon: 149.1, type: 'country' },
  { name: 'United Kingdom', lat: 51.5, lon: -0.1, type: 'country' },
  { name: 'France', lat: 48.85, lon: 2.35, type: 'country' },
  { name: 'Germany', lat: 52.5, lon: 13.4, type: 'country' },
  { name: 'Japan', lat: 35.7, lon: 139.7, type: 'country' },
  { name: 'South Africa', lat: -25.7, lon: 28.2, type: 'country' },
  { name: 'Egypt', lat: 30.0, lon: 31.2, type: 'country' },
  { name: 'Canada', lat: 45.4, lon: -75.7, type: 'country' },
  { name: 'Mexico', lat: 19.4, lon: -99.1, type: 'country' },
  { name: 'Indonesia', lat: -6.2, lon: 106.8, type: 'country' },
  { name: 'Nigeria', lat: 9.1, lon: 7.5, type: 'country' },
  { name: 'Argentina', lat: -34.6, lon: -58.4, type: 'country' },
  { name: 'Saudi Arabia', lat: 24.7, lon: 46.7, type: 'country' },
  { name: 'Italy', lat: 41.9, lon: 12.5, type: 'country' },
  { name: 'Spain', lat: 40.4, lon: -3.7, type: 'country' },
  { name: 'South Korea', lat: 37.6, lon: 127.0, type: 'country' },
  { name: 'Thailand', lat: 13.75, lon: 100.5, type: 'country' },
  { name: 'Kenya', lat: -1.3, lon: 36.8, type: 'country' },
  { name: 'New Zealand', lat: -41.3, lon: 174.8, type: 'country' },
  { name: 'Norway', lat: 59.9, lon: 10.75, type: 'country' },
  { name: 'Sri Lanka', lat: 6.9, lon: 79.85, type: 'country' },
  { name: 'Mumbai', lat: 19.07, lon: 72.87, type: 'city' },
  { name: 'Chennai', lat: 13.08, lon: 80.27, type: 'city' },
  { name: 'Kolkata', lat: 22.57, lon: 88.36, type: 'city' },
  { name: 'Visakhapatnam', lat: 17.68, lon: 83.22, type: 'city' },
  { name: 'Kochi', lat: 9.93, lon: 76.26, type: 'city' },
  { name: 'Panaji', lat: 15.49, lon: 73.83, type: 'city' },
  { name: 'Puri', lat: 19.8, lon: 85.83, type: 'city' },
  { name: 'Surat', lat: 21.17, lon: 72.83, type: 'city' },
]