// Deep sea bathymetric features: Hadal trenches, mid-ocean ridges, seamounts.

export const SEABED_FEATURES = [
  {
    id: 'mariana-trench',
    name: 'Mariana Trench (Challenger Deep)',
    type: 'hadal_trench',
    ocean: 'Western Pacific',
    lat: 11.373,
    lon: 142.592,
    depth_m: 10994,
    pressure_atm: 1086,
    description: 'The deepest known point on Earth. Hydrostatic pressure exceeds 1,000 atmospheres in complete darkness.',
    color: '#a855f7',
  },
  {
    id: 'puerto-rico-trench',
    name: 'Puerto Rico Trench (Milwaukee Deep)',
    type: 'hadal_trench',
    ocean: 'Atlantic Ocean',
    lat: 19.84,
    lon: -66.5,
    depth_m: 8376,
    pressure_atm: 827,
    description: 'Deepest point in the Atlantic Ocean and Caribbean boundary zone with complex subduction geodynamics.',
    color: '#c084fc',
  },
  {
    id: 'java-trench',
    name: 'Java (Sunda) Trench',
    type: 'hadal_trench',
    ocean: 'Eastern Indian Ocean',
    lat: -10.3,
    lon: 109.9,
    depth_m: 7725,
    pressure_atm: 763,
    description: 'Deepest point in the Indian Ocean, formed by Indo-Australian plate subducting under the Sunda plate.',
    color: '#d8b4fe',
  },
  {
    id: 'tonga-trench',
    name: 'Tonga Trench (Horizon Deep)',
    type: 'hadal_trench',
    ocean: 'South Pacific Ocean',
    lat: -23.29,
    lon: -174.72,
    depth_m: 10882,
    pressure_atm: 1075,
    description: 'Second deepest trench on Earth, known for having the fastest plate tectonic convergence rate on the planet.',
    color: '#a855f7',
  },
  {
    id: 'mid-atlantic-ridge',
    name: 'Mid-Atlantic Ridge (Hydrothermal Vent Fields)',
    type: 'ridge',
    ocean: 'Central Atlantic',
    lat: 26.13,
    lon: -44.83,
    depth_m: 2500,
    pressure_atm: 247,
    description: 'Submerged volcanic mountain range splitting the Atlantic. Home to TAG hydrothermal black smoker vents.',
    color: '#38bdf8',
  },
  {
    id: 'great-barrier-reef',
    name: 'Great Barrier Reef (Coral Sea Lagoon)',
    type: 'reef',
    ocean: 'South Pacific / Coral Sea',
    lat: -18.28,
    lon: 147.7,
    depth_m: 35,
    pressure_atm: 4.5,
    description: 'The world\'s largest living coral structure, hyper-sensitive to sea surface thermal anomalies and bleaching.',
    color: '#34d399',
  },
  {
    id: 'diamantina-deep',
    name: 'Diamantina Deep (Fracture Zone)',
    type: 'fracture',
    ocean: 'Southeast Indian Ocean',
    lat: -35.2,
    lon: 104.9,
    depth_m: 7019,
    pressure_atm: 693,
    description: 'Rugged tectonic fracture zone southwest of Perth, surveyed during deep-sea ocean floor mapping.',
    color: '#818cf8',
  },
]
